name: Generate API References

on:
  workflow_dispatch:
    inputs:
      groupdocs_library:
        description: 'Select library to generate references for'
        required: true
        default: 'GroupDocs.Conversion.LowCode'
        type: choice
        options:
          - GroupDocs.Conversion.LowCode
          #- GroupDocs.Merger.LowCode
          #- GroupDocs.Metadata.LowCode

run-name: Generate API refs for ${{ inputs.groupdocs_library }}

env:
  AWS_REGION: us-west-2

jobs:
  generate-refs:
    name: Generate API References
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: groupdocs-net/groupdocs-net
          token: ${{ secrets.READ_PAT }}
          ref: main
          fetch-depth: 0

      - name: Set output folder
        id: setup
        run: |
          LIBRARY="${{ github.event.inputs.groupdocs_library }}"
          
          case "$LIBRARY" in
            "GroupDocs.Conversion.LowCode")
              OUTPUT_FOLDER="conversion"
              ;;
            "GroupDocs.Merger.LowCode")
              OUTPUT_FOLDER="merger"
              ;;
            "GroupDocs.Metadata.LowCode")
              OUTPUT_FOLDER="metadata"
              ;;
            *)
              echo "Unknown library: $LIBRARY"
              exit 1
              ;;
          esac
          
          echo "output_folder=$OUTPUT_FOLDER" >> $GITHUB_OUTPUT
          echo "Selected output folder: $OUTPUT_FOLDER"

      - name: Build Docker image
        run: |
          cd ./utils/api-refs-generator/
          docker build -t groupdocs-api-refs-generator .

      - name: Generate API references
        run: |
          cd ./utils/api-refs-generator/
          docker run -it --rm \
            -v "$(pwd)/../../content/reference.groupdocs.net/${{ steps.setup.outputs.output_folder }}/":/app/output \
            groupdocs-api-refs-generator \
            "${{ github.event.inputs.groupdocs_library }}"

      - name: Check for changes and commit
        run: |
          cd content/reference.groupdocs.net/
          
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are any changes
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes detected in reference content"
          else
            echo "Changes detected, committing..."
            git add .
            git commit -m "Update API references for ${{ github.event.inputs.groupdocs_library }}
            
            Generated by: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
            Triggered by: ${{ github.actor }}"
            
            git push origin main
            echo "Changes committed and pushed successfully"
          fi